/**
 * Local filesystem storage — for development, for `next start` on your own machine, and for
 * Docker/self-hosted deployments with a volume. Not usable on Vercel, where the only writable
 * directory is `/tmp` and it is wiped between invocations.
 *
 * Objects are served by the app itself (`/api/storage/local/<key>`), protected by the same
 * HMAC signatures the presigned cloud drivers use, so the client code is identical.
 */

import { createReadStream, createWriteStream } from "node:fs";
import { mkdir, rm, stat, writeFile } from "node:fs/promises";
import path from "node:path";
import { Readable } from "node:stream";
import { pipeline } from "node:stream/promises";

import { signPayload, verifyPayload } from "./signing";
import { StorageError, type ObjectBody, type ObjectHead, type Storage, type UploadTarget } from "./types";

export function storageRoot(dir?: string): string {
  return path.resolve(dir ?? process.env.STORAGE_DIR ?? "./.data/storage");
}

/** Keys are generated by the app, but never trust a key that arrives from outside. */
export function safeKey(key: string): string {
  const cleaned = key.replace(/\\/g, "/").replace(/^\/+/, "");
  if (!cleaned || cleaned.includes("..") || cleaned.includes("\0")) {
    throw new StorageError(`unsafe storage key: ${key}`);
  }
  return cleaned;
}

export function objectPath(root: string, key: string): string {
  return path.join(root, safeKey(key));
}

export class LocalStorage implements Storage {
  readonly driver = "local" as const;
  readonly label: string;
  readonly #root: string;
  readonly #baseUrl: string;

  constructor(options: { dir?: string; baseUrl: string }) {
    this.#root = storageRoot(options.dir);
    this.#baseUrl = options.baseUrl.replace(/\/+$/, "");
    this.label = `Local filesystem · ${this.#root}`;
  }

  #url(key: string, token: string): string {
    return `${this.#baseUrl}/api/storage/local/${encodeURIComponent(safeKey(key))}?token=${token}`;
  }

  async createUploadTarget(options: {
    key: string;
    contentType?: string;
    maxBytes?: number;
    expiresInSeconds?: number;
  }): Promise<UploadTarget> {
    const expiresInSeconds = options.expiresInSeconds ?? 3600;
    const token = signPayload({
      key: safeKey(options.key),
      op: "put",
      exp: Date.now() + expiresInSeconds * 1000,
      maxBytes: options.maxBytes,
      contentType: options.contentType,
    });
    const headers: Record<string, string> = {};
    if (options.contentType) headers["content-type"] = options.contentType;
    return {
      url: this.#url(options.key, token),
      method: "PUT",
      headers,
      key: options.key,
      driver: "local",
      expiresInSeconds,
      maxBytes: options.maxBytes,
    };
  }

  async createDownloadUrl(
    key: string,
    options?: { expiresInSeconds?: number; downloadName?: string },
  ): Promise<string> {
    const expiresInSeconds = options?.expiresInSeconds ?? 3600;
    const token = signPayload({
      key: safeKey(key),
      op: "get",
      exp: Date.now() + expiresInSeconds * 1000,
      name: options?.downloadName,
    });
    return this.#url(key, token);
  }

  /** Used by the `/api/storage/local` route, which validates the token itself. */
  targetFor(key: string, token: string): string {
    return objectPath(this.#root, key);
  }

  async getObject(key: string): Promise<ObjectBody | null> {
    const file = objectPath(this.#root, key);
    try {
      const info = await stat(file);
      if (!info.isFile()) return null;
      const stream = Readable.toWeb(createReadStream(file)) as ReadableStream<Uint8Array>;
      return { body: stream, size: info.size };
    } catch {
      return null;
    }
  }

  async putObject(key: string, body: Uint8Array, _contentType?: string): Promise<ObjectHead> {
    const file = objectPath(this.#root, key);
    await mkdir(path.dirname(file), { recursive: true });
    await writeFile(file, body);
    return { size: body.byteLength, contentType: _contentType ?? null };
  }

  /** Streaming write used by the local upload route, so large uploads do not fill memory. */
  async putStream(key: string, stream: ReadableStream<Uint8Array>): Promise<ObjectHead> {
    const file = objectPath(this.#root, key);
    await mkdir(path.dirname(file), { recursive: true });
    await pipeline(Readable.fromWeb(stream as Parameters<typeof Readable.fromWeb>[0]), createWriteStream(file));
    const info = await stat(file);
    return { size: info.size };
  }

  async headObject(key: string): Promise<ObjectHead | null> {
    try {
      const info = await stat(objectPath(this.#root, key));
      if (!info.isFile()) return null;
      return { size: info.size };
    } catch {
      return null;
    }
  }

  async deleteObject(key: string): Promise<void> {
    await rm(objectPath(this.#root, key), { force: true });
  }

  async test(): Promise<{ ok: boolean; detail: string }> {
    const key = `_healthcheck/${Date.now()}.txt`;
    const payload = new TextEncoder().encode("video-convertor storage check");
    try {
      await this.putObject(key, payload, "text/plain");
      const read = await this.getObject(key);
      const text = read?.body ? await new Response(read.body).text() : "";
      await this.deleteObject(key);
      if (text !== "video-convertor storage check") {
        return { ok: false, detail: "wrote a test file but read different content back" };
      }
      return { ok: true, detail: `read and wrote ${this.#root}` };
    } catch (error) {
      return { ok: false, detail: error instanceof Error ? error.message : String(error) };
    }
  }
}

export function verifyLocalToken(token: string, expectedOp: "put" | "get") {
  const payload = verifyPayload(token);
  if (!payload || payload.op !== expectedOp) return null;
  return payload;
}
